name: 'Check Quest update'

on:
  schedule:
    - cron: '0 0 * * *' # At every day 00:00(UTC).

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Check Update
        id: check-update
        run: npm run checkPoi

      - name: Push Branch
        run: |
          git config user.name 'kcwikizh'
          git config user.email 'dev@kcwiki.moe'
          git add draft
          git commit --message 'feat(data): draft new quest' || true
          git remote set-url origin "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
          git push --force origin HEAD:bot/new-quest
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # see https://github.com/repo-sync/pull-request
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2.2
        with:
          source_branch: 'bot/new-quest' # If blank, default: triggered branch
          pr_title: New quest (${{ steps.date.outputs.date }}) # Title of pull request
          pr_body: ${{ join(steps.check-update.outputs.*, '') }} # Full markdown support, requires pr_title to be set
          pr_label: 'data,bot' # Comma-separated list (no spaces)
          github_token: ${{ secrets.GITHUB_TOKEN }}
